# Generated by Django 5.1.3 on 2024-11-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
    ]
