# Generated by Django 5.1.3 on 2024-11-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('sum_loan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percent_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('loan_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'credit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('number_document', models.CharField(max_length=30)),
                ('date_birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('appointment', models.CharField(max_length=30)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_item', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inventory', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=50)),
                ('info_product', models.TextField()),
                ('appraised_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('photo_link', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_item', models.CharField(max_length=50)),
                ('info_item', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPledge',
            fields=[
                ('pledge_id', models.AutoField(primary_key=True, serialize=False)),
                ('pledge_date', models.DateField()),
                ('condition_pledge', models.CharField(blank=True, max_length=20, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('loan_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_pledge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_payment_give', models.DateField()),
                ('date_payment_return', models.DateField(blank=True, null=True)),
                ('sum_payment_give', models.DecimalField(decimal_places=2, max_digits=10)),
                ('way_payment_give', models.CharField(max_length=30)),
                ('sum_payment_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('way_payment_return', models.CharField(blank=True, max_length=39, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatedItem',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_rating', models.DateField()),
                ('description_item', models.TextField()),
            ],
            options={
                'db_table': 'rated_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_report', models.DateField()),
                ('total_amount_transactions', models.DecimalField(decimal_places=2, max_digits=13)),
                ('amount_pledge_sum', models.DecimalField(decimal_places=2, max_digits=13)),
                ('amount_sold_item_sum', models.DecimalField(decimal_places=2, max_digits=13)),
                ('amount_pledge', models.IntegerField(blank=True, null=True)),
                ('amount_sold_item', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_sell', models.DateField()),
                ('price_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sold_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionPayment',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_trans', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction_payment',
                'managed': False,
            },
        ),
    ]
